image: archlinux
packages:
    - rustup
    - python
    - python-matplotlib
    - git
    - netcdf
sources:
    - https://git.sr.ht/~axect/Peroxide
tasks:
    - setup: |
        rustup toolchain install nightly
        cd Peroxide/
        rustup run nightly cargo fetch
    - nightly: |
        rustup default nightly
        cd Peroxide/
        cargo build --verbose ||:
        cargo test --verbose ||:
    - docs: |
        rustup default nightly
        cd Peroxide/
        RUSTDOCFLAGS='--html-in-header katex-header.html' cargo doc --no-deps ||:

