language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose
  - cargo test --verbose
  - RUSTDOCFLAGS='--html-in-header katex-header.html' cargo doc --no-deps